- Say your team's name to the person pointing to the left in the bedroom
- Give me a cup from the shelf
- Meet Yoshimura in the study room and escort them to the tall table
- Navigate to the study room then meet Andrew and follow them to the dining room
- Meet Jack at the right tray then locate them in the study room
- Answer the quiz of the person giving the V sign in the study room
- Answer the question of the person pointing to the left in the living room
- Tell me what is the thinnest object on the low table
- Tell me what is the heaviest object on the shelf
